title: Karolina Czarnecka
name: Oficjalna witryna
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://localhost:4000" # development
url: "https://karolinaczarnecka.pl" # production
# url: "https://dwoznicka.github.io/czarneckak" # github pages

copyright: 2020 © <a href="https://karolinaczarnecka.pl" class="site-link">Karolina Czarnecka</a>. Wszelkie prawa zastrzeżone.
copyright_short: 2020 © <a href="https://karolinaczarnecka.pl" class="site-link">Karolina Czarnecka</a>.
made_by: ''
# Build settings
markdown: kramdown
incremental: true
gems:
  - jekyll-watch
  - jekyll-assets
exclude:
- CNAME
- .gitignore
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- .ruby-version
- Guardfile
- .jekyll-assets-cache
- .sass-cache
- .editorconfig
- .idea
- .ruby-version
- .asset-cache
- _docs

#
# Plugin: jekyll-assets
#
assets:
  cache: false
  features:
    automatic_img_size: false
    automatic_img_alt: false
